# Generated by Django 4.0.6 on 2022-07-16 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shortedlink_long_url_shortedlink_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortedlink',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
